version: '3.4'

services:
  catalog:
    image: events/productcatalogapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_catalog$
    volumes:
      - C:\Users\Monica\Desktop\Kal\EventsHub\EventsHub\ProductCatalogAPI:/app
      - C:\Users\Monica\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_catalog$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_catalog$ bin/Debug/netcoreapp2.1/ProductCatalogAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

  tokenserver:
    image: tokenserver:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_tokenserver$
    volumes:
      - C:\Users\Monica\Desktop\Kal\EventsHub\EventsHub\TokenServiceApi:/app
      - C:\Users\Monica\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_tokenserver$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_tokenserver$ bin/Debug/netcoreapp2.1/TokenServiceApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""


  webmvc:
    image: webmvc:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webmvc$
    volumes:
      - C:\Users\Monica\Desktop\Kal\EventsHub\EventsHub\WebMVC:/app
      - C:\Users\Monica\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_webmvc$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webmvc$ bin/Debug/netcoreapp2.1/WebMVC.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

